/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pr3_3;

import java.util.regex.*;

/**
 *
 * @author showland17
 */
public class EventFrame extends javax.swing.JFrame {
    
    int sortStatus;
    FileIO dateIO = new FileIO("C:\\Users\\showland17\\Documents\\GitHub\\CS372-Java-Apps\\PR3_3\\dates\\dates.txt");
    AppointmentManager manager = new AppointmentManager();
    
    /**
     * Creates new form EventFrame
     */
    public EventFrame() {
        initComponents();
        readAppts();
        printAppts();
    }
    
    /**
     * Prints every Appointment currently stored in the manager to the text 
     * display area
     */
    private void printAppts() {
        for (Appointment s : manager.appointments()) {
            String appt = s.Title() + " : " + s.Location() + " : " + s.Date();
            fldApptArea.append(appt);
            fldApptArea.append("\n");
        }
    }
    
    /**
     * Reads all appointments from the file set aside for the EventFrame
     */
    private void readAppts() {
        dateIO.ReadAll(manager.appointments());
        manager.dateSort();
        sortStatus = 0;
    }
    
    /**
     * Parses the user's date input. If it matches the format for a yyyy/mm/dd 
     * entry, then a new appointment is added to the manager using the user's
     * inputs, then written to the file set aside for the EventFrame
     */
    private void addAppt() {
        int intDate = 0;
        String dateText = DateEntryField.getText();
        Pattern p = Pattern.compile( "((19|20))\\d{2}[- /.](0?[1-9]|1[012])[- /.](0?[1-9]|[12][0-9]|3[01])");
        Matcher m = p.matcher(dateText);
        
        //If the parsing fails, we don't want to take any action
        if (m.find()) {
            String nameText = NameEntryField.getText();
            String locText = LocationEntryField.getText();
            String appt = nameText + "" + locText + "" + dateText;
            manager.appointments().add(new Appointment (nameText, locText, dateText));
            dateIO.Write(nameText, locText, dateText);
            
            if (sortStatus == 0)
               manager.dateSort();
            else if (sortStatus == 1)
                manager.titleSort();
            else
                manager.locationSort();
            fldApptArea.setText("");
            printAppts();
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DateEntryField = new javax.swing.JTextField();
        AddEvent = new javax.swing.JButton();
        NameEntryField = new javax.swing.JTextField();
        LocationEntryField = new javax.swing.JTextField();
        Header = new javax.swing.JLabel();
        TitleSort = new javax.swing.JButton();
        LocationSort = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fldApptArea = new javax.swing.JTextArea();
        DateSort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DateEntryField.setText("yyyy/mm/dd");

        AddEvent.setText("Add Event!");
        AddEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEventActionPerformed(evt);
            }
        });

        NameEntryField.setText("Name");

        LocationEntryField.setText("Location");

        Header.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Header.setText("Your Calendar");

        TitleSort.setText("Title");
        TitleSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TitleSortActionPerformed(evt);
            }
        });

        LocationSort.setText("Location");
        LocationSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationSortActionPerformed(evt);
            }
        });

        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        fldApptArea.setColumns(20);
        fldApptArea.setRows(5);
        jScrollPane2.setViewportView(fldApptArea);

        DateSort.setText("Date");
        DateSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Header)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LocationEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DateEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddEvent))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TitleSort, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LocationSort)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DateSort))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Header)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddEvent)
                    .addComponent(NameEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LocationEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TitleSort)
                        .addComponent(DateSort))
                    .addComponent(LocationSort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * When the "Location" button is pressed, the manager sorts its Appointment
     * array by location, clears the current displayed text, then prints the
     * sorted list
     * @param evt 
     */
    private void LocationSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationSortActionPerformed
        manager.locationSort();
        sortStatus = 2;
        fldApptArea.setText("");
        printAppts();
    }//GEN-LAST:event_LocationSortActionPerformed

    /**
     * Starts the parsing/list updating/file writing process
     * @param evt The user's button press
     */
    private void AddEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEventActionPerformed
            addAppt();
    }//GEN-LAST:event_AddEventActionPerformed

    /**
     * When the "Title" button is pressed, the manager sorts its Appointment
     * array by title, clears the current displayed text, then prints the
     * sorted list
     * @param evt The user's button press
     */
    private void TitleSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TitleSortActionPerformed
        manager.titleSort();
        sortStatus = 1;
        fldApptArea.setText("");
        printAppts();
    }//GEN-LAST:event_TitleSortActionPerformed

    /**
     * When the "Date" button is pressed, the manager sorts its Appointment
     * array by date, clears the current displayed text, then prints the
     * sorted list
     * @param evt The user's button press
     */
    private void DateSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateSortActionPerformed
         manager.dateSort();
         sortStatus = 0;
        fldApptArea.setText("");
        printAppts();
    }//GEN-LAST:event_DateSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEvent;
    private javax.swing.JTextField DateEntryField;
    private javax.swing.JButton DateSort;
    private javax.swing.JLabel Header;
    private javax.swing.JTextField LocationEntryField;
    private javax.swing.JButton LocationSort;
    private javax.swing.JTextField NameEntryField;
    private javax.swing.JButton TitleSort;
    private javax.swing.JTextArea fldApptArea;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
