/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pr4_1;

import java.util.ArrayList;
import java.io.*;
/**
 *
 * @author Scott
 */
public class Reviewer extends javax.swing.JFrame {

    private ArrayList<Review> reviews = new ArrayList();
    private File dir, database;
    private FileIO reviewRW;
    private int rating = -1;
    private String reviewBlocks = "";
    
    /**
     * Creates new form Reviewer
     */
    public Reviewer() {
        initComponents();
        setupFiles();
        buildRatingGroup();
        
        try {
            reviewRW.readReviews(reviews);
            getRevText();
        }
        
        catch (Exception ex) {
            System.out.println("Error initializing notes pane");
        }
    }
    
    private void getRevText() {
        reviewBlocks = "";
        for (Review r : reviews) {
            reviewBlocks += assembleReview(r.establishment(), r.address(), r.notes(), r.rating()) + "\n";
        }
        
        if (!reviews.isEmpty()) {
            ReviewPane.setText(reviewBlocks);
        }
    }
    
    private void setupFiles() {
        dir = new File("notes");        
        try {
            dir.mkdirs();
        }
        catch (Exception ex) {
            System.out.println("Error creating file directory");
        }   
        
        database = new File(dir, "reviews.txt");
        try {
            database.createNewFile();
        }
        catch (IOException ex) {
            System.out.println("Error creating database file");
        }
        
        reviewRW = new FileIO(database.getPath());
    }
    
    private void buildRatingGroup() {
        RatingGroup.add(OneRating);
        RatingGroup.add(TwoRating);
        RatingGroup.add(ThreeRating);
        RatingGroup.add(FourRating);
        RatingGroup.add(FiveRating);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RatingGroup = new javax.swing.ButtonGroup();
        ReviewerTabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AddReview = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        NotePane = new javax.swing.JTextPane();
        OneRating = new javax.swing.JRadioButton();
        FiveRating = new javax.swing.JRadioButton();
        TwoRating = new javax.swing.JRadioButton();
        ThreeRating = new javax.swing.JRadioButton();
        FourRating = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReviewPane = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Restaurant Name:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Address:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("5-Star Rating:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Additional Notes");

        AddReview.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AddReview.setText("Add A New Review");
        AddReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddReviewActionPerformed(evt);
            }
        });

        NameField.setText("Ex: Dave's Joint");
        NameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        AddressField.setText("Ex: 1234 Main Street, Spokane");
        AddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFieldActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(NotePane);

        OneRating.setText("1");
        OneRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneRatingActionPerformed(evt);
            }
        });

        FiveRating.setText("5");
        FiveRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveRatingActionPerformed(evt);
            }
        });

        TwoRating.setText("2");
        TwoRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoRatingActionPerformed(evt);
            }
        });

        ThreeRating.setText("3");
        ThreeRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeRatingActionPerformed(evt);
            }
        });

        FourRating.setText("4");
        FourRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourRatingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AddReview)
                                .addGap(0, 88, Short.MAX_VALUE))
                            .addComponent(AddressField)
                            .addComponent(NameField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(31, 31, 31)
                                .addComponent(OneRating)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TwoRating)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThreeRating)
                                .addGap(2, 2, 2)
                                .addComponent(FourRating)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FiveRating)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(AddReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(OneRating)
                    .addComponent(FiveRating)
                    .addComponent(TwoRating)
                    .addComponent(ThreeRating)
                    .addComponent(FourRating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addContainerGap())
        );

        ReviewerTabs.addTab("Add Review", jPanel1);

        ReviewPane.setEditable(false);
        ReviewPane.setColumns(20);
        ReviewPane.setRows(5);
        jScrollPane2.setViewportView(ReviewPane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        ReviewerTabs.addTab("Old Reviews", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ReviewerTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ReviewerTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFieldActionPerformed

    private void ThreeRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeRatingActionPerformed
        rating = 3;
    }//GEN-LAST:event_ThreeRatingActionPerformed

    private void FourRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourRatingActionPerformed
        rating = 4;
    }//GEN-LAST:event_FourRatingActionPerformed

    private void AddReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddReviewActionPerformed
        String establishment="", address="", notes="";
        
        try {
            establishment = NameField.getText();
            address = AddressField.getText();
            notes = NotePane.getText();
            if (rating == -1) 
                throw new IllegalArgumentException();
            
            Review newReview = new Review(establishment, address, notes, rating);
            reviews.add(newReview);
            getRevText();
            ReviewPane.setText(reviewBlocks);
        }
        
        catch (Exception ex) {
            System.out.println("Error creating review. Check input.");
        }
    }//GEN-LAST:event_AddReviewActionPerformed

    private void OneRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneRatingActionPerformed
        rating  = 1;
    }//GEN-LAST:event_OneRatingActionPerformed

    private void TwoRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoRatingActionPerformed
        rating = 2;
    }//GEN-LAST:event_TwoRatingActionPerformed

    private void FiveRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveRatingActionPerformed
        rating = 5;
    }//GEN-LAST:event_FiveRatingActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        reviewRW.writeReviews(reviews);
    }//GEN-LAST:event_formWindowClosing

     private String assembleReview(String name, String address, String notes, int rating) {
         String review = "Restaurant: " + name + "\n";
         review += "Location: " + address + "\n";
         review += "Rating: " + rating + "/5\n";
         review += "Additional notes: " + notes + "\n";
         
         return review;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reviewer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reviewer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddReview;
    private javax.swing.JTextField AddressField;
    private javax.swing.JRadioButton FiveRating;
    private javax.swing.JRadioButton FourRating;
    private javax.swing.JTextField NameField;
    private javax.swing.JTextPane NotePane;
    private javax.swing.JRadioButton OneRating;
    private javax.swing.ButtonGroup RatingGroup;
    private javax.swing.JTextArea ReviewPane;
    private javax.swing.JTabbedPane ReviewerTabs;
    private javax.swing.JRadioButton ThreeRating;
    private javax.swing.JRadioButton TwoRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
